### ISSUE TITLE
中间件启动报错

### ISSUE THREAD

**Issue by Sistercon** [catbaron0/efb-msg_blocker-middleware#1]
报错如下
`File "/usr/local/bin/ehforwarderbot", line 11, in <module>
    load_entry_point('ehforwarderbot==2.0.0b28', 'console_scripts', 'ehforwarderbot')()
  File "/home/sjdx/.local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 263, in main
    conf = config.load_config()
  File "/home/sjdx/.local/lib/python3.6/site-packages/ehforwarderbot/config.py", line 75, in load_config
    raise ValueError(_("\"{}\" is not found.").format(i))
ValueError: "catbaron.message_blocker" is not found.`

**Comment by catbaron0** [comment]
这个报错看上去是没有安装成功……
顺便说一下我刚把中间件重写了，可以尝试更新一下看看

**Comment by Sistercon** [comment]
没问题了   已经可用

**Comment by oocococo** [comment]
> 没问题了 已经可用

可以问问是怎么解决的吗，我也遇到了同样的问题，同样的报错，是今天才安装的

**Comment by catbaron0** [comment]
e

> > 没问题了 已经可用
> 
> 可以问问是怎么解决的吗，我也遇到了同样的问题，同样的报错，是今天才安装的

安装的时候有报错么？

**Comment by oocococo** [comment]
> e
> 
> > > 没问题了 已经可用
> > 
> > 
> > 可以问问是怎么解决的吗，我也遇到了同样的问题，同样的报错，是今天才安装的
> 
> 安装的时候有报错么？

安装时候的日志https://pastebin.com/47V2MWEG   应该是没有报错

**Comment by catbaron0** [comment]
> > e
> > > > 没问题了 已经可用
> > > 
> > > 
> > > 可以问问是怎么解决的吗，我也遇到了同样的问题，同样的报错，是今天才安装的
> > 
> > 
> > 安装的时候有报错么？
> 
> 安装时候的日志https://pastebin.com/47V2MWEG 应该是没有报错

群里大佬建议检查一下安装中间件和 EFB 的运行环境 python 是不是同一个。
有进展推荐在群里讨论

**Comment by oocococo** [comment]
> > > e
> > > > > 没问题了 已经可用
> > > > 
> > > > 
> > > > 可以问问是怎么解决的吗，我也遇到了同样的问题，同样的报错，是今天才安装的
> > > 
> > > 
> > > 安装的时候有报错么？
> > 
> > 
> > 安装时候的日志https://pastebin.com/47V2MWEG 应该是没有报错
> 
> 群里大佬建议检查一下安装中间件和 EFB 的运行环境 python 是不是同一个。
> 有进展推荐在群里讨论

不好意思这几天没看这个，
所有的包我都是使用pip3 install xxx --user 和 python3 setup.py install --user安装的，为了确保无误，我将中间件的包使用root也安装了一遍，但是还是出现相同的报错、
PS：请问讨论群是哪一个

**Comment by catbaron0** [comment]
@oocococo 讨论群请查看 https://t.me/EFBSupport

**Comment by catbaron0** [comment]
@oocococo 
刚发现你的配置应该写错了
中间件是 `catbaron.msg_blocker` 而非 `catbaron.message_blocker`
如果还有问题请再开新的 issue

**Comment by arrio464** [comment]
> @oocococo 刚发现你的配置应该写错了 中间件是 `catbaron.msg_blocker` 而非 `catbaron.message_blocker` 如果还有问题请再开新的 issue

建议将readme里的
`Middleware ID: catbaron.message_blocker`
改为
`Middleware ID: catbaron.msg_blocker`
以方便后人。
由于这个issue已关闭，人们不一定会注意到😂
（比如说我就差不多花了一个小时来排查这个问题😂
